### ISSUE TITLE
go-stash in windows 10，报错

### ISSUE THREAD

**Issue by SmartZou** [Mikaelemmmm/go-zero-looklook#108]
go-stash配置
```
  go-stash:
    image: kevinwan/go-stash:1.0 
    container_name: go-stash
    environment:
      TZ: Asia/Shanghai
    user: root
    restart: always
    volumes:
      - ./deploy/go-stash/etc:/app/etc
    networks:
      - search_net
    depends_on:
      - elasticsearch
      - kafka
```

go-stash 报错
```
{"@timestamp":"2023-04-28T10:42:48.852+08","level":"error","content":"queue.go:170 Error on reading message, \"[15] Group Coordinator Not Available: the broker returns this error code for group coordinator requests, offset commits, and most group management requests if the offsets topic has not yet been created, or if the group coordinator is not active\""}
```
