### ISSUE TITLE
go-stash Group Coordinator Not Available

### ISSUE THREAD

**Issue by ericdong2012** [Mikaelemmmm/go-zero-looklook#16]
基于docker-compose-env.yaml 中 完成 filebeat -- kafka -- go-stash -- es --kibana 日志收集部署，容器启动后发现go-stash 报错， 日志如下：
```
{"@timestamp":"2022-02-20T17:25:15.412+08","level":"error","content":"queue.go:170 Error on reading message, \"[15] Group Coordinator Not Available: the broker returns this error code for group coordinator requests, offset commits, and most group management requests if the offsets topic has not yet been created, or if the group coordinator is not active\""}

```
日志显示kafka group coordinator 存在问题

docker-compose 中 kafka 信息如下：

```

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    # host ip
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - ./data/kafka/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - gse_net
```

整个文件目录结构如下:
```
deploy
-- data 
    -- kafka 
        -- docker.sock

-- go-stash
-- filebeat
docker-compose.yaml

```

解决方案:

删除deploy/data/kafka/ 下的文件：  cd deploy && rm -rf data/kafka/*
重新启动：docker-compose  up --force-recreate -d 

问题解决

**Comment by ericdong2012** [comment]
docker-compose 中 kafka 信息如下：

```

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    # host ip
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - ./data/kafka/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - gse_net
```

整个文件目录结构如下:
```
deploy
-- data 
    -- kafka 
        -- docker.sock

-- go-stash
-- filebeat
docker-compose.yaml

```

解决方案:

删除deploy/data/kafka/ 下的文件：  cd deploy && rm -rf data/kafka/*
重新启动：docker-compose  up --force-recreate -d 

问题解决
