### ISSUE TITLE
go-stash配置es密码

### ISSUE THREAD

**Issue by ysongyang** [Mikaelemmmm/go-zero-looklook#47]
不知道是否正确
```
Output:
      ElasticSearch:
        Hosts:
          - "http://elasticsearch:9200"
        Index: "dev-{{yyyy-MM-dd}}"
        User: "elastic"
        Password: "elastic"
```
