### ISSUE TITLE
lyumikael/gomodd:v1.0.0 镜像不支持 go 1.8

### ISSUE THREAD

**Issue by loyalpartner** [Mikaelemmmm/go-zero-looklook#66]
lyumikael/gomodd:v1.0.0 不支持 go1.8

然后我自己做了个Dockerfile

```
FROM golang AS builder

ENV GOPROXY=https://goproxy.cn,direct
ENV GO111MODULE=on

RUN go version
RUN go install github.com/cortesi/modd/cmd/modd@latest

CMD [ "modd" ]
```

我这个 docker 镜像运行后 文件改动后 modd 不会重启应用，请问你的 Dockerfile 是怎么实现的呢？

**Comment by loyalpartner** [comment]
是我的配置文件写错了 - -！！

**Comment by NX-Official** [comment]
所以这个问题的正确解决方式是？

**Comment by NX-Official** [comment]
解决了🙏，使用这个Dockerfile编译之后在docker-compose中使用即可
```
    #image: lyumikael/gomodd:v1.0.0 # if you "macOs intel" or "linux amd"
#    image: lyumikael/go-modd-env:v1.0.0  # if you macOs m1
    build:
     context: .
     dockerfile: deploy/moddDockerFile
```
