### ISSUE TITLE
prometheus怎么发现k8s集群里的服务的？

### ISSUE THREAD

**Issue by ip520011** [Mikaelemmmm/go-zero-looklook#80]
As mentioned in Chapters 14 and 15 of the document, mysql, Prometheus and other middleware are deployed on the SRV-data.com server, which is independent of the K8S cluster. However, I saw that the promethean. Yml configuration file has the promethean port for each service exposure, such as

` ` `

- job_name: 'order-api'

static_configs:

- targets: [ 'looklook:4001' ]

labels:

job: order-api

app: order-api

env: dev

` ` `

So how does Prometheus find them, and how does this configuration change

如题，大佬，文档第14，15章写到，mysql、prometheus等中间件都是部署在srv-data.com服务器上，是独立于k8s集群的，但是我看到prometheus.yml配置文件里有写各个服务暴露的的prometheus端口，如 
```
  - job_name: 'order-api'
    static_configs:
      - targets: [ 'looklook:4001' ]
        labels:
          job: order-api
          app: order-api
          env: dev
```
那prometheus怎么发现他们呢，这块配置该怎么改呢
